layout_spectrum: 0
color:
  saturation: 0.8134457
  brandStrength: 0.6989247
  lightness: 0.9954553
  rhythmicContrast: 0.09387729
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.6845878
name: Picturegraphing adventures
